[package]
name = "key-path"
description = "Key path for Rust."
license = "MIT"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
